[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "./node_modules/typescript/lib"}, environment = "node"}

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls", "emmet-ls"]
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-astro", "--parser", "astro"] }
auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "emmet-ls"]
formatter = { command = "prettier", args = ["--parser", "typescript" ] }
auto-format = true

[[language]]
name = "markdown"
file-types = ["md", "mdx"]
