[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "./node_modules/typescript/lib"}, environment = "node"}

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls", "emmet-ls", "biome"]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "emmet-ls", "biome" ]
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "emmet-ls", "biome" ]
auto-format = true

[[language]]
name = "json"
language-servers = [ "biome" ]
auto-format = true

[[language]]
name = "markdown"
file-types = ["md", "mdx"]

