"""First migration

Revision ID: 1e99703f8998
Revises: 
Create Date: 2022-03-30 17:34:52.872031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e99703f8998'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('resource_uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('resource_uuid')
    )
    op.create_index(op.f('ix_resources_resource_uuid'), 'resources', ['resource_uuid'], unique=False)
    op.create_table('entries',
    sa.Column('resource_uuid', sa.String(), nullable=True),
    sa.Column('entry_uuid', sa.String(), nullable=False),
    sa.Column('private_body', sa.String(), nullable=True),
    sa.Column('public_body', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resource_uuid'], ['resources.resource_uuid'], ),
    sa.PrimaryKeyConstraint('entry_uuid')
    )
    op.create_index(op.f('ix_entries_entry_uuid'), 'entries', ['entry_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_entry_uuid'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_resources_resource_uuid'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
