"""use Enum for state

Revision ID: 6741ba40c976
Revises: b03375db6ae3
Create Date: 2022-04-20 20:23:49.140604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6741ba40c976'
down_revision = 'b03375db6ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
