"""use JSON instead of String

Revision ID: b03375db6ae3
Revises: 1e99703f8998
Create Date: 2022-04-20 20:18:08.473182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03375db6ae3'
down_revision = '1e99703f8998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
