baseURL = "https://gildedernacht.ch/"
DefaultContentLanguage = "de"
theme = "gilde-der-nacht"
themesDir = "../../themes"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
  [languages.de]
    title = "Gilde der Nacht"
    weight = 1
    languageName = "Deutsch"
    [languages.de.params]
      footer = "Luzerner Spielverein"
      [languages.de.params.page]
        title = "Über uns"
        text = "Die **Gilde der Nacht** ist ein Luzerner Spielverein. Seit 2011 organisieren wir Anlässe, Spieltreffen und -wochenende in der Stadt Luzern und wirken bei anderen spielorientierten Projekten – auch ausserhalb der Stadtgrenze – mit."
      [languages.de.params.network]
        [languages.de.params.network.spieltage]
          title = "Luzerner Spieltage"
          text = "Das Spielwochenende für jung und alt. <br /> [Erfahre mehr ...](https://spieltage.ch/)"
          logo = "spieltage"
        [languages.de.params.network.rollenspieltage]
          title = "Luzerner Rollenspieltage"
          text = "Zwei Tage in die fantastische Welt der Rollenspiele abtauchen. <br /> [Erfahre mehr ...](https://rollenspieltage.ch/)"
          logo = "rollenspieltage"

  [languages.en]
    title = "Gilde der Nacht"
    weight = 2
    languageName = "English"
    [languages.en.params]
      footer = "Game association based in Lucerne"

[params]
  discord = "https://discord.gg/G7mkTTB"
  facebook = "https://www.facebook.com/GildederNacht/"
  meetup = "https://www.meetup.com/de-DE/Spieltreffen-Luzern"
