name: Deploy Olymp

on:
  push:
    tags: [olymp*]
  workflow_dispatch:

jobs:
  deploy-olymp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Deploy
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ${{ secrets.DOCKER_HOST }}
          remote_docker_port: ${{ secrets.DOCKER_PORT }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          stack_file_name: ./olymp/docker-compose.deploy.yml
          pull_images_first: true
          args: up -d --build
