name: Fetch Events

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'


jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "7040739+Level8Broccoli@users.noreply.github.com"
        curl \
          "https://www.googleapis.com/calendar/v3/calendars/gildedernacht%40gmail.com/events?timeMin=$(date +'%Y-%m-%dT%T.000Z')&key=AIzaSyBRXYQfvv3KHyZmZrhxzWDOghX_c7xfnGo" \
          --header 'Accept: application/json' \
          --compressed \
          -o websites/gildedernacht.ch/data/calendar.json
        git add .
        git commit -m "fetch new event data"
        git push
