name: Fetch Olymp Events

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run script
        shell: bash
        run: |
          docker compose -f scripts/fetchOlympEvents/docker-compose.yml up

      - name: move output
        shell: bash
        run: |
          mv scripts/fetchOlympEvents/out/olymp.json ssg/websites/gildedernacht.ch/data/olymp.json

      - name: commit if changed
        shell: bash
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "7040739+Level8Broccoli@users.noreply.github.com"

          git diff --quiet && git diff --staged --quiet || git commit -am 'fetch new olymp event data' && git push
