name: gildedernacht.ch Live Page

on:
  push:
    tags: [v*]
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  deploy-live-pages:
    name: ${{ matrix.site }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
         - site: gildedernacht
           siteCode: gdn

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: yarn install

      - run: yarn ${{ matrix.siteCode }}-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: gilde-der-nacht/${{ matrix.site }}.ch
          publish_branch: master
          publish_dir: ./dist/${{ matrix.site }}.ch
          cname: ${{ matrix.site }}.ch
