name: spieltage.ch Test Page

on:
  push:
    branches: [dandelion-*]
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  deploy-test-pages:
    name: test.${{ matrix.site }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
         - site: spieltage
           siteCode: lst

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: yarn install

      - run: yarn ${{ matrix.siteCode }}-build
        env:
          ENV: test

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: gilde-der-nacht/test.${{ matrix.site }}.ch
          publish_branch: master
          publish_dir: ./dist/${{ matrix.site }}.ch
          cname: test.${{ matrix.site }}.ch
